### ISSUE TITLE
Build CC scanning route

### ISSUE THREAD

**Issue by philawsophizing** [FACN1/pod#15]
- [x] #60 - 4hr - Send data to cloud vision
- [x] #63 - 1hr - Store in session storage
- [x] # - 1hr - Forward to bar code scanner 
- [x] #54 - 2hr - Generate token (maybe JWT)

Ref #7.
