### ISSUE TITLE
Bar code scanning route

### ISSUE THREAD

**Issue by philawsophizing** [FACN1/pod#16]
## [CLICK FOR NEW TODO](#issuecomment-299704859)

- [x] Capture bar code picture
- [x] Parse with quaggajs
- [x] Send to bar code API
- [x] Forward to shopping cart route

Ref #8.

**Comment by macintoshhelper** [comment]
## UPDATE

- [x] Barcode should be on cart page instead of a separate route.
- [ ] `/add-item` route receives post request and uses OCR to extract barcode

**Comment by macintoshhelper** [comment]
## TODO

- [ ] # - Upload image to Cloud Vision and get text response
- [ ] # - Hardcoded list of items in the database to get details from
- [ ] # - Add item to shopping cart session (local storage + JSON)
