### ISSUE TITLE
Tech setup

### ISSUE THREAD

**Issue by macintoshhelper** [FACN1/pod#19]
- [x] #22 Setup npm / package.json
- [x] #23 Setup Hapi - routes, vision, etc
- [x] #24 Setup Heroku + PostgreSQL
- [x] #25 Setup code coverage
- [x] #26 Setup airbnb linter
- [x] #32 Setup travis
