### ISSUE TITLE
As a consumer, I want to buy items in a shop using my phone

### ISSUE THREAD

**Issue by macintoshhelper** [FACN1/pod#6]
## User Stories
+ [ ] #7 Be able to start a shopping experience when entering a shop.
+ [ ] #8 Add/remove/update items quickly in my shopping cart.
+ [ ] #9 View details of my shopping experience.
+ [ ] #10 Automatically pay for my purchases when I leave the shop.
